services:
  - type: web
    name: securenet-ids-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ABUSEIPDB_API_KEY
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: OTX_API_KEY
        sync: false
      - key: URLSCAN_API_KEY
        sync: false
      - key: GOOGLE_SAFE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
