import React, { useState } from 'react';
import { FiDownload, FiFileText, FiAlertTriangle, FiDatabase, FiCalendar, FiShield } from 'react-icons/fi';
import { jsPDF } from 'jspdf';
import { logsData } from '../data/logs';

const Reports = () => {
  const [isGenerating, setIsGenerating] = useState(null);

  const generateLogsReport = () => {
    setIsGenerating('logs');
    
    setTimeout(() => {
      const pdf = new jsPDF();
      
      // Add custom font for better appearance
      pdf.setFontSize(20);
      pdf.setTextColor(0, 245, 255); // Neon blue color
      pdf.text('SecureNet IDS - Logs Report', 20, 25);
      
      pdf.setFontSize(12);
      pdf.setTextColor(255, 255, 255);
      pdf.text(`Generated on: ${new Date().toLocaleString()}`, 20, 40);
      
      // Add summary statistics
      pdf.setFontSize(14);
      pdf.setTextColor(0, 245, 255);
      pdf.text('Summary Statistics', 20, 60);
      
      pdf.setFontSize(10);
      pdf.setTextColor(255, 255, 255);
      
      const criticalCount = logsData.filter(log => log.riskLevel === 'CRITICAL').length;
      const highCount = logsData.filter(log => log.riskLevel === 'HIGH').length;
      const mediumCount = logsData.filter(log => log.riskLevel === 'MEDIUM').length;
      const lowCount = logsData.filter(log => log.riskLevel === 'LOW').length;
      const blockedCount = logsData.filter(log => log.blocked).length;
      
      pdf.text(`Total Entries: ${logsData.length}`, 20, 75);
      pdf.text(`Critical Threats: ${criticalCount}`, 20, 85);
      pdf.text(`High Risk: ${highCount}`, 20, 95);
      pdf.text(`Medium Risk: ${mediumCount}`, 20, 105);
      pdf.text(`Low Risk: ${lowCount}`, 20, 115);
      pdf.text(`Blocked Attacks: ${blockedCount}`, 20, 125);
      pdf.text(`Block Rate: ${((blockedCount / logsData.length) * 100).toFixed(1)}%`, 20, 135);
      
      // Add detailed logs table header
      pdf.setFontSize(14);
      pdf.setTextColor(0, 245, 255);
      pdf.text('Detailed Logs', 20, 155);
      
      pdf.setFontSize(8);
      pdf.setTextColor(200, 200, 200);
      
      // Table headers
      const headers = ['IP Address', 'Prediction', 'Risk', 'Status', 'Time'];
      const columnWidths = [40, 50, 25, 25, 50];
      let xPos = 20;
      
      headers.forEach((header, index) => {
        pdf.text(header, xPos, 170);
        xPos += columnWidths[index];
      });
      
      // Table data (first 10 logs for demo)
      pdf.setTextColor(255, 255, 255);
      let yPos = 180;
      
      logsData.slice(0, 10).forEach(log => {
        xPos = 20;
        
        // Truncate long strings to fit
        const ip = log.ipAddress.length > 15 ? log.ipAddress.substring(0, 12) + '...' : log.ipAddress;
        const prediction = log.prediction.length > 20 ? log.prediction.substring(0, 17) + '...' : log.prediction;
        const time = new Date(log.timestamp).toLocaleString().substring(0, 10);
        
        pdf.text(ip, xPos, yPos);
        xPos += columnWidths[0];
        
        pdf.text(prediction, xPos, yPos);
        xPos += columnWidths[1];
        
        // Color code risk levels
        if (log.riskLevel === 'CRITICAL') {
          pdf.setTextColor(255, 59, 59); // Red
        } else if (log.riskLevel === 'HIGH') {
          pdf.setTextColor(255, 140, 0); // Orange
        } else if (log.riskLevel === 'MEDIUM') {
          pdf.setTextColor(255, 200, 87); // Yellow
        } else {
          pdf.setTextColor(34, 255, 136); // Green
        }
        
        pdf.text(log.riskLevel, xPos, yPos);
        xPos += columnWidths[2];
        
        pdf.setTextColor(255, 255, 255);
        pdf.text(log.blocked ? 'BLOCKED' : 'MONITORED', xPos, yPos);
        xPos += columnWidths[3];
        
        pdf.text(time, xPos, yPos);
        
        yPos += 10;
        
        // Add new page if needed
        if (yPos > 270) {
          pdf.addPage();
          yPos = 20;
        }
      });
      
      // Add footer
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text('This report was generated by SecureNet IDS - Advanced Threat Detection System', 20, 280);
      
      // Save the PDF
      pdf.save('securenet-logs-report.pdf');
      setIsGenerating(null);
    }, 1500);
  };

  const generateAlertsReport = () => {
    setIsGenerating('alerts');
    
    setTimeout(() => {
      const pdf = new jsPDF();
      
      // Add custom styling
      pdf.setFontSize(20);
      pdf.setTextColor(255, 59, 59); // Neon red for alerts
      pdf.text('SecureNet IDS - Alerts Report', 20, 25);
      
      pdf.setFontSize(12);
      pdf.setTextColor(255, 255, 255);
      pdf.text(`Generated on: ${new Date().toLocaleString()}`, 20, 40);
      
      // Alert summary
      pdf.setFontSize(14);
      pdf.setTextColor(255, 59, 59);
      pdf.text('Alert Summary', 20, 60);
      
      pdf.setFontSize(10);
      pdf.setTextColor(255, 255, 255);
      
      // Sample alert data (in real app, this would come from alerts state)
      const alertSummary = [
        { type: 'Critical Alerts', count: 47, color: 'HIGH PRIORITY' },
        { type: 'High Risk Alerts', count: 128, color: 'ELEVATED' },
        { type: 'Medium Risk Alerts', count: 289, color: 'GUARDED' },
        { type: 'Low Risk Alerts', count: 567, color: 'LOW' }
      ];
      
      alertSummary.forEach((alert, index) => {
        const yPos = 75 + (index * 15);
        pdf.text(`${alert.type}: ${alert.count} (${alert.color})`, 20, yPos);
      });
      
      // Recent critical alerts
      pdf.setFontSize(14);
      pdf.setTextColor(255, 59, 59);
      pdf.text('Recent Critical Alerts', 20, 145);
      
      pdf.setFontSize(9);
      pdf.setTextColor(255, 255, 255);
      
      const criticalAlerts = logsData
        .filter(log => log.riskLevel === 'CRITICAL')
        .slice(0, 8);
      
      let yPos = 160;
      criticalAlerts.forEach((alert, index) => {
        yPos = 160 + (index * 12);
        const time = new Date(alert.timestamp).toLocaleString();
        
        pdf.text(`• ${alert.prediction} from ${alert.ipAddress}`, 25, yPos);
        pdf.text(`  ${time}`, 25, yPos + 5);
        
        if (yPos > 260) {
          pdf.addPage();
          yPos = 20;
        }
      });
      
      // Recommendations
      pdf.setFontSize(14);
      pdf.setTextColor(0, 245, 255);
      pdf.text('Security Recommendations', 20, 220);
      
      pdf.setFontSize(9);
      pdf.setTextColor(255, 255, 255);
      
      const recommendations = [
        '• Immediate investigation required for critical alerts',
        '• Review firewall rules for blocked IPs',
        '• Consider implementing additional monitoring for high-risk sources',
        '• Regular security audits recommended',
        '• Update threat intelligence databases'
      ];
      
      recommendations.forEach((rec, index) => {
        pdf.text(rec, 25, 235 + (index * 8));
      });
      
      // Add footer
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text('This report was generated by SecureNet IDS - Advanced Threat Detection System', 20, 280);
      
      // Save the PDF
      pdf.save('securenet-alerts-report.pdf');
      setIsGenerating(null);
    }, 1500);
  };

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-white mb-2">Security Reports</h1>
          <p className="text-gray-400">Generate comprehensive security analysis reports</p>
        </div>
        <div className="flex items-center space-x-2">
          <FiCalendar className="text-neon-blue" size={20} />
          <span className="text-sm text-neon-blue">Last Report: Never</span>
        </div>
      </div>

      {/* Report Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Logs Report Card */}
        <div className="glass-card p-8 hover-glow transition-all duration-300">
          <div className="flex items-center space-x-4 mb-6">
            <div className="p-4 bg-neon-blue/20 rounded-lg border border-neon-blue/30">
              <FiDatabase size={32} className="text-neon-blue" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-white mb-1">Generate Logs Report</h2>
              <p className="text-gray-400">Comprehensive system logs analysis</p>
            </div>
          </div>

          <div className="space-y-4 mb-6">
            <div className="flex items-center justify-between text-sm">
              <span className="text-gray-400">Total Entries:</span>
              <span className="text-neon-blue font-semibold">{logsData.length}</span>
            </div>
            <div className="flex items-center justify-between text-sm">
              <span className="text-gray-400">Critical Threats:</span>
              <span className="text-neon-red font-semibold">
                {logsData.filter(log => log.riskLevel === 'CRITICAL').length}
              </span>
            </div>
            <div className="flex items-center justify-between text-sm">
              <span className="text-gray-400">Block Rate:</span>
              <span className="text-neon-green font-semibold">
                {((logsData.filter(log => log.blocked).length / logsData.length) * 100).toFixed(1)}%
              </span>
            </div>
          </div>

          <button
            onClick={generateLogsReport}
            disabled={isGenerating === 'logs'}
            className={`
              w-full flex items-center justify-center space-x-3 px-6 py-3 rounded-lg
              font-semibold transition-all duration-300 relative overflow-hidden
              ${isGenerating === 'logs'
                ? 'bg-gray-600 text-gray-400 cursor-not-allowed'
                : 'bg-neon-blue/20 border border-neon-blue text-neon-blue hover:bg-neon-blue/30 hover:scale-105 hover-glow'
              }
            `}
          >
            {isGenerating === 'logs' ? (
              <>
                <div className="w-5 h-5 border-2 border-neon-blue border-t-transparent rounded-full animate-spin"></div>
                <span>Generating...</span>
              </>
            ) : (
              <>
                <FiDownload size={20} />
                <span>Download PDF Report</span>
              </>
            )}
          </button>
        </div>

        {/* Alerts Report Card */}
        <div className="glass-card p-8 hover-glow transition-all duration-300">
          <div className="flex items-center space-x-4 mb-6">
            <div className="p-4 bg-neon-red/20 rounded-lg border border-neon-red/30">
              <FiAlertTriangle size={32} className="text-neon-red" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-white mb-1">Generate Alerts Report</h2>
              <p className="text-gray-400">Security alerts and threat analysis</p>
            </div>
          </div>

          <div className="space-y-4 mb-6">
            <div className="flex items-center justify-between text-sm">
              <span className="text-gray-400">Active Alerts:</span>
              <span className="text-neon-red font-semibold">
                {logsData.filter(log => log.riskLevel === 'CRITICAL').length}
              </span>
            </div>
            <div className="flex items-center justify-between text-sm">
              <span className="text-gray-400">High Priority:</span>
              <span className="text-orange-500 font-semibold">
                {logsData.filter(log => log.riskLevel === 'HIGH').length}
              </span>
            </div>
            <div className="flex items-center justify-between text-sm">
              <span className="text-gray-400">Response Rate:</span>
              <span className="text-neon-green font-semibold">94.2%</span>
            </div>
          </div>

          <button
            onClick={generateAlertsReport}
            disabled={isGenerating === 'alerts'}
            className={`
              w-full flex items-center justify-center space-x-3 px-6 py-3 rounded-lg
              font-semibold transition-all duration-300 relative overflow-hidden
              ${isGenerating === 'alerts'
                ? 'bg-gray-600 text-gray-400 cursor-not-allowed'
                : 'bg-neon-red/20 border border-neon-red text-neon-red hover:bg-neon-red/30 hover:scale-105 hover-glow'
              }
            `}
          >
            {isGenerating === 'alerts' ? (
              <>
                <div className="w-5 h-5 border-2 border-neon-red border-t-transparent rounded-full animate-spin"></div>
                <span>Generating...</span>
              </>
            ) : (
              <>
                <FiDownload size={20} />
                <span>Download PDF Report</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Additional Report Options */}
      <div className="glass-card p-6">
        <h3 className="text-xl font-semibold text-white mb-4">Additional Report Options</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="p-4 bg-white/5 rounded-lg border border-white/10">
            <div className="flex items-center space-x-3 mb-2">
              <FiFileText className="text-neon-blue" size={20} />
              <span className="text-white font-semibold">Custom Report</span>
            </div>
            <p className="text-sm text-gray-400">Generate reports with custom date ranges and filters</p>
          </div>
          <div className="p-4 bg-white/5 rounded-lg border border-white/10">
            <div className="flex items-center space-x-3 mb-2">
              <FiShield className="text-neon-green" size={20} />
              <span className="text-white font-semibold">Compliance Report</span>
            </div>
            <p className="text-sm text-gray-400">Generate reports for security compliance requirements</p>
          </div>
          <div className="p-4 bg-white/5 rounded-lg border border-white/10">
            <div className="flex items-center space-x-3 mb-2">
              <FiCalendar className="text-neon-yellow" size={20} />
              <span className="text-white font-semibold">Scheduled Reports</span>
            </div>
            <p className="text-sm text-gray-400">Set up automated report generation and delivery</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
